name: Test Build

on:
  push:
    branches: [ master ]

jobs:
  build-crafti:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependancies
      run: |
          sudo apt update
          sudo apt install git libc6-armel-cross libc6-dev-armel-cross binutils-arm-linux-gnueabi libncurses5-dev build-essential bison flex libssl-dev bc build-essential autoconf automake gdb git libffi-dev zlib1g-dev gcc binutils libgmp-dev libmpfr-dev libmpc-dev zlib1g wget libboost-program-options-dev sed libc6 libc-bin -y
          
    - name: Build Ndless-SDK
      run: |
          git clone --recursive https://github.com/ndless-nspire/Ndless.git
          cd Ndless/ndless-sdk/toolchain/
          ./build_toolchain.sh
          echo "/home/runner/work/crafti/crafti/Ndless/ndless-sdk/toolchain/install/bin" >> $GITHUB_PATH
          echo "/home/runner/work/crafti/crafti/Ndless/ndless-sdk/bin" >> $GITHUB_PATH
          cd ../..
          make -j$(nproc --all)
          
    - name: Upload Build Artifacts (1)
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ndless-sdk-bin
        path: $GITHUB_WORKSPACE/ndless-sdk/bin/*
        
    - name: Upload Build Artifacts (2)
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ndless-sdk-bin
        path: $GITHUB_WORKSPACE/ndless-sdk/toolchain/install/bin/*
