name: Contributors List

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  contribute-list:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Contribute List
      uses: akhilmhdh/contributors-readme-action@v2.3.4
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

