name: Contributors List

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Contribute List
      uses: akhilmhdh/contributors-readme-action@v2.3.4

