name: Test Build

on:
  push:
    branches: [ master ]

env:
  GITHUB_PATH: $HOME/work/crafti/crafti/.github/workflows/ndless-sdk-bin/

jobs:
  install-dependancies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: |
          sudo apt install git gcc binutils libgmp-dev libmpfr-dev libmpc-dev zlib1g zlib1g-dev wget libboost-program-options-dev -y
          ls $HOME/work/crafti/crafti
          pwd
          ls -a
          nspire-gcc
