name: Test Build

on:
  push:
    branches: [ master ]

jobs:
  install-dependancies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: |
          git clone --recursive https://github.com/ndless-nspire/Ndless.git
          cd Ndless/ndless-sdk/toolchain/
          ./build_toolchain.sh 
